pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "565257597039"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    /* parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    } */

    // Build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Bastion EKS ACM') {
            parallel {
                stage('Trigger Bastion') {
                    steps {
                        script {
                            build job: '20-bastion',
                                propagate: false,
                                wait: false
                        }
                    }
                }

                stage('Trigger EKS') {
                    steps {
                        script {
                            build job: '80-eks',
                                propagate: false,
                                wait: false
                        }
                    }
                }

                stage('ACM') {
                    steps {
                        script {
                            build job: '60-acm',
                                propagate: true,
                                wait: false
                        }
                    }
                }
            }
        }

        stage('ALB') {
            steps {
                script {
                    build job: '70-frontend-alb',
                        propagate: true,
                        wait: false
                }
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}